// Generated by CoffeeScript 1.6.3
/*
(c) 2011 Jan Monschke
v1.0.1
GeoMock is licensed under the MIT license.
*/


(function() {
  (function() {
    if (typeof navigator === "undefined" || navigator === null) {
      window.navigator = {};
    }
    if (navigator.geolocation == null) {
      window.navigator.geolocation = {};
    }
    navigator.geolocation.delay = 2000;
    navigator.geolocation.shouldFail = false;
    navigator.geolocation.failsAt = -1;
    navigator.geolocation.errorMessage = "There was an error retrieving the position!";
    navigator.geolocation.currentTimeout = -1;
    navigator.geolocation.lastPosReturned = 0;
    navigator.geolocation._sanitizeLastReturned = function() {
      if (this.lastPosReturned > this.waypoints.length - 1) {
        return this.lastPosReturned = 0;
      }
    };
    navigator.geolocation._geoCall = function(method, success, error) {
      var _this = this;
      if (this.shouldFail && (error != null)) {
        return this.currentTimeout = window[method].call(null, function() {
          return error(_this.errorMessage);
        }, this.delay);
      } else {
        if (success != null) {
          return this.currentTimeout = window[method].call(null, function() {
            success(_this.waypoints[_this.lastPosReturned++]);
            return _this._sanitizeLastReturned();
          }, this.delay);
        }
      }
    };
    navigator.geolocation.getCurrentPosition = function(success, error) {
      return this._geoCall("setTimeout", success, error);
    };
    navigator.geolocation.watchPosition = function(success, error) {
      this._geoCall("setInterval", success, error);
      return this.currentTimeout;
    };
    navigator.geolocation.clearWatch = function(id) {
      return clearInterval(id);
    };
    return navigator.geolocation.waypoints = [
      {
        coords: {
          latitude: 52.5168,
          longitude: 13.3889,
          accuracy: 1500,
          speed: 0.5
        }
      }, {
        coords: {
          latitude: 52.5162,
          longitude: 13.3890,
          accuracy: 1334,
          speed: 11
        }
      }, {
        coords: {
          latitude: 52.5154,
          longitude: 13.3890,
          accuracy: 631,
          speed: 12
        }
      }, {
        coords: {
          latitude: 52.5150,
          longitude: 13.3890,
          accuracy: 361,
          speed: 20
        }
      }, {
        coords: {
          latitude: 52.5144,
          longitude: 13.3890,
          accuracy: 150,
          speed: 22
        }
      }, {
        coords: {
          latitude: 52.5138,
          longitude: 13.3890,
          accuracy: 65,
          speed: 23
        }
      }, {
        coords: {
          latitude: 52.5138,
          longitude: 13.3895,
          accuracy: 65,
          speed: 24
        }
      }, {
        coords: {
          latitude: 52.5139,
          longitude: 13.3899,
          accuracy: 65,
          speed: 25
        }
      }, {
        coords: {
          latitude: 52.5140,
          longitude: 13.3906,
          accuracy: 65,
          speed: 26
        }
      }, {
        coords: {
          latitude: 52.5140,
          longitude: 13.3910,
          accuracy: 65,
          speed: 27
        }
      }
    ];
  })();

}).call(this);